### ISSUE TITLE
Lookup response invalid argument exception

### ISSUE THREAD

**Issue by bryanrite** [donnen/TaxCloud#2]
Looks like a basic LookupResponse object throws a Invalid Argument exception:

``` ruby
ArgumentError:
       wrong number of arguments(1 for 0)
```

This is because LookupResponse, which inherits BaseResponse calls `super` in `initialize`.  BaseResponse cannot handle the call to super and bails.

I've monkey patched LookupResponse to not call `super` in the meantime but this is unlikely the desired behaviour.

**Comment by donnen** [comment]
Hi, I haven't been able to duplicate this. What version of Ruby are you
using? Are you able to run the tests in lookup_service_spec.rb?

**Comment by bryanrite** [comment]
I'm using 1.9.3-p327

I'll try and come up with a minimal code example that fails today.
